---
environment-1:
  workspaces:
    workspace-1:
      description: "This is workspace 1 in environment 1"
    workspace-2:
      description: "This is workspace 2 in environment 1"
environment-2-all-options:
  default_provider_configurations:
    - "default-provider-1"
    - "default-provider-2"
  default_workspace_agent_pool_id: "default-agent-pool-1"
  federated_environments:
    - "federated-env-1"
    - "federated-env-2"
  mask_sensitive_output: true
  remote_backend: true
  remote_backend_overridable: false
  storage_profile_id: "storage-profile-1"
  tag_ids:
    - "tag-1"
    - "tag-2"
  workspaces:
    workspace-3-all-options:
      agent_pool_id: "agent-pool-1"
      auto_apply: false
      auto_queue_runs: "skip_first" # possible values: "always", "never", "skip_first", "on_create_only"
      deletion_protection_enabled: true
      description: "This is workspace 3 in environment 2"
      execution_mode: "remote" # possible values: "local", "remote"
      force_latest_run: false
      iac_platform: "opentofu" # possible values: "terraform", "opentofu"
      module_version_id: "module-version-1"
      provider_configuration:
        - "provider-1"
        - "provider-2"
      remote_backend: true
      remote_state_consumers:
        - "consumer-1"
        - "consumer-2"
      run_operation_timeout: 30 # in minutes
      ssh_key_id: "ssh-key-1"
      tag_ids:
        - "tag-1"
        - "tag-2"
      terraform_version: "1.5.0"
      type: "development" # possible values: "development", "production", "staging", "testing", "unmapped"
      var_files:
        - "var-file-1"
        - "var-file-2"
      working_directory: "/path/to/working/directory"
      vcs_repo:
        - branch: "main"
          dry_runs_enabled: true
          identifier: "org/repo"
          ingress_submodules: false
          trigger_patterns:
            - "*.tf"
          trigger_prefixes:
            - "stage"
            - "prod"
            - "dev"
